#include "Slic3r/App/Plater/SlaSupportPointsLeaving.hpp"

#include "Slic3r/Domain/ModelObject.hpp"

namespace Slic3r::App::Plater {

bool apply_generated_points_on_leaving(bool has_generated_points, bool discard_requested)
{
    if (!has_generated_points) {
        return false;
    }
    return !discard_requested;
}

void
apply_generated_support_points(Domain::ModelObject& model_object, Domain::SLA::SupportPoints points)
{
    model_object.sla_support_points = std::move(points);
    model_object.sla_points_status  = Domain::SLA::PointsStatus::AutoGenerated;
}

} // namespace Slic3r::App::Plater
