#pragma once

#include <cstdint>


#include "Slic3r/Domain/Constants.hpp"
#include "Slic3r/Domain/Point.hpp"

namespace Slic3r::Domain::SLA {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Reason of automatic support placement usage
enum class SupportPointType {
    manual_add,
    island, // no move, island should be grouped
    slope,
    //thin,
    //stability,
    //edge
};

/// <summary>
/// Stereolithography(SLA) support point
/// </summary>
struct SupportPoint
{
    // Position on model surface
    Vec3f pos = Vec3f::Zero(); // [in mm]

    // radius of the touching interface
    // Also define force it must keep
    float head_front_radius = 0.f; // [in mm]

    // type
    SupportPointType type{SupportPointType::manual_add};

    // Per-point pillar (stem) diameter override. 0 = use global config.
    float pillar_diameter = 0.f; // [in mm]

    // Per-point base diameter override. 0 = use global config.
    float base_diameter = 0.f; // [in mm]

    // Per-point base height override. 0 = use global config.
    float base_height = 0.f; // [in mm]

    // Tip shape for this point. Default keeps the standard pinhead geometry.
    enum class TipShape : uint8_t { Default, Cone, Ball };
    TipShape tip_shape = TipShape::Default;

    // Per-point tip length override. 0 = use global config (head width).
    float tip_length = 0.f; // [in mm]

    // Per-point contact depth override (how far the tip sinks in). 0 = use global penetration.
    float contact_depth = 0.f; // [in mm]

    // Per-point stem cross-section. 0 = use global (round); 4 = square, 6 = hexagon, and so on.
    uint8_t stem_sides = 0;

    // Per-point stem taper: fraction of the stem diameter lost from base to tip. 0 = no taper.
    float stem_taper = 0.f;

    // Radius of a ball at the tip-to-stem joint. 0 = no knot.
    float knot_radius = 0.f; // [in mm]


    bool is_island() const { return type == SupportPointType::island; }

    // unsaved changes + cache invalidation
    bool operator==(const SupportPoint &sp) const;

    bool operator!=(const SupportPoint &sp) const;

};
using SupportPoints = std::vector<SupportPoint>;

} // namespace Slic3r::Domain::SLA
