#pragma once

#include <cstdint>


#include "Slic3r/Domain/Constants.hpp"
#include "Slic3r/Domain/Point.hpp"

namespace Slic3r::Domain::SLA {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Reason of automatic support placement usage
enum class SupportPointType {
    manual_add,
    island, // no move, island should be grouped
    slope,
    //thin,
    //stability,
    //edge
};

/// <summary>
/// Stereolithography(SLA) support point
/// </summary>
struct SupportPoint
{
    // Position on model surface
    Vec3f pos = Vec3f::Zero(); // [in mm]

    // radius of the touching interface
    // Also define force it must keep
    float head_front_radius = 0.f; // [in mm]

    // type
    SupportPointType type{SupportPointType::manual_add};

    // Per-point pillar (stem) diameter override. 0 = use global config.
    float pillar_diameter = 0.f; // [in mm]

    // Per-point base diameter override. 0 = use global config.
    float base_diameter = 0.f; // [in mm]

    // Per-point base height override. 0 = use global config.
    float base_height = 0.f; // [in mm]

    // Shape of the foot where the pillar of this point meets the raft or the plate.
    // Default keeps the globally configured shape.
    enum class BaseShape : uint8_t { Default, Cone, Cylinder, Flat };
    BaseShape base_shape = BaseShape::Default;

    // Tip shape for this point. Default keeps the standard pinhead geometry.
    // Cone replaces the front sphere with a point, Ball with a ball of the front
    // radius.
    enum class TipShape : uint8_t { Default, Cone, Ball };
    TipShape tip_shape = TipShape::Default;

    // Per-point tip length override. 0 = use global config (head width).
    float tip_length = 0.f; // [in mm]

    // Per-point contact depth override (how far the tip sinks in). 0 = use global penetration.
    float contact_depth = 0.f; // [in mm]

    // Per-point stem cross-section. 0 = use global (round); 4 = square, 6 = hexagon, and so on.
    // Only 3 to 12 sides are built, anything else falls back to the round pillar.
    uint8_t stem_sides = 0;

    // Per-point stem taper: in mm how much less the pillar radius is at its base
    // than at its head end, changing linearly along the pillar. 0 = no taper.
    // The result never drops below the minimum pillar radius.
    float stem_taper = 0.f; // [in mm]

    // Radius of a ball at the tip-to-stem joint. 0 = no knot.
    float knot_radius = 0.f; // [in mm]

    // Whether the pillar of this point may end on the model surface instead of
    // reaching the build plate. Inherit leaves the decision to the object's
    // "supports must not end on the model" (support_buildplate_only), which is
    // what every point did before the switch existed (M2.26).
    enum class OnModel : uint8_t { Inherit, Allow, Forbid };
    OnModel on_model = OnModel::Inherit;

    // What this point carries, which is what the tip class of its support is
    // picked from (M7.8.2, the support rulebook R4.1 and R4.3 - R4.6 of
    // doc/sla-fork/supports/rulebook.md): the anchor of the lowest island, an
    // island, a small island, an overhang, or a fragile thin feature. Unknown is
    // what a point placed by hand carries, and what a project written before the
    // roles existed reads back as, so an older file keeps the point it had.
    //
    // AnchorLarge is the anchor of a very large object (M7.8.3, the size table of
    // rulebook section 3), which takes the largest tip (T0.6) instead of the heavy
    // one. It is appended at the end and the values before it are never renumbered,
    // so a project written before it reads back as it was.
    enum class Role : uint8_t
    {
        Unknown,
        Anchor,
        Island,
        SmallIsland,
        Overhang,
        Fragile,
        AnchorLarge
    };
    Role role = Role::Unknown;

    bool is_island() const { return type == SupportPointType::island; }

    // unsaved changes + cache invalidation
    bool operator==(const SupportPoint &sp) const;

    bool operator!=(const SupportPoint &sp) const;

};
using SupportPoints = std::vector<SupportPoint>;

} // namespace Slic3r::Domain::SLA
