#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "Slic3r/Biz/ArchiveIni.hpp"
#include "Slic3r/Biz/ResinProfile/ChituboxCfgReader.hpp"
#include "Slic3r/Biz/ResinProfile/ResinProfileReaderRegistry.hpp"
#include "Slic3r/Biz/ResinProfile/SlicedArchiveResinReader.hpp"
#include "Slic3r/Biz/ResultExport/SLA/Zipper.hpp"

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include <cstddef>
#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <vector>

#include "miniz.h"

using namespace Slic3r::Biz::ResinProfile;

using Catch::Approx;

namespace fs = boost::filesystem;

namespace {

// The metadata of a job as the archive writer puts it in config.ini. Hand written, so that
// the test does not depend on what a slicing run happens to produce. It states no bottom
// layer count: an archive that carries one, under the numBottom key the writer adds, is the
// case of the round trip in Sl1ImportTests.cpp, and a hand written numBottom is the case
// below.
const std::string CONFIG_INI =
    "# generated by a slicer\n"
    "version = 1\n"
    "expTime = 2.5\n"
    "expTimeFirst = 30\n"
    "expUserProfile = 2\n"
    "layerHeight = 0.05\n"
    "numFade = 4\n"
    "numSlow = 2\n"
    "numFast = 8\n"
    "materialName = Grey Resin\n"
    "materialVendor = Some Resin Co\n"
    "printerModel = SL1\n"
    "printerVariant = 1.7\n"
    "printTime = 3600\n"
    "usedMaterial = 1.5\n";

// The profile of the same job, as it is embedded in prusaslicer.ini. It names the very same
// settings differently, which is what the reader has to resolve.
const std::string PROFILE_INI =
    "exposure_time = 2.5\n"
    "initial_exposure_time = 30\n"
    "layer_height = 0.05\n"
    "initial_layer_height = 0.2\n"
    "faded_layers = 4\n"
    "bottom_layer_count = 6\n"
    "sla_material_settings_id = Grey Resin\n"
    "material_vendor = Some Resin Co\n"
    "display_width = 144\n"
    "display_pixels_x = 1440\n";

// The fixture archives are built under the working directory of the test run, so a test
// leaves nothing behind outside the build tree.
class LocalDir
{
public:
    LocalDir()
        : m_path{fs::current_path() / "sliced-archive-resin-reader-tests"}
    {
        boost::system::error_code ec;
        fs::create_directories(m_path, ec);
    }

    ~LocalDir()
    {
        boost::system::error_code ec;
        fs::remove_all(m_path, ec);
    }

    LocalDir(const LocalDir&)            = delete;
    LocalDir& operator=(const LocalDir&) = delete;

    const fs::path& path() const { return m_path; }

private:
    fs::path m_path;
};

void write_text(const fs::path& path, const std::string& contents)
{
    boost::filesystem::ofstream out{path, std::ios::binary};
    out << contents;
}

fs::path write_archive(const fs::path& path,
                       const std::map<std::string, std::string>& entries,
                       Slic3r::Biz::PrintHost::Sla::Zipper::e_compression compression
                           = Slic3r::Biz::PrintHost::Sla::Zipper::FAST_COMPRESSION)
{
    Slic3r::Biz::PrintHost::Sla::Zipper zipper{path.string(), compression};
    for (const auto& [name, data] : entries)
        zipper.add_entry(name, data.data(), data.size());
    zipper.finalize();
    return path;
}

// One entry of a zip that is written out byte by byte, so a test can make the central
// directory of an entry claim a size the data does not have. That is the shape of a zip
// bomb, and a writer of ours cannot be asked for one.
struct RawEntry
{
    std::string   name;
    std::string   data;
    std::uint32_t declared_uncomp_size = 0; // 0 claims the real size of the data
    std::uint16_t method                = 0; // 0 is stored, 8 is deflate
};

void put_u16(std::string& out, std::uint16_t value)
{
    out.push_back(static_cast<char>(value & 0xffu));
    out.push_back(static_cast<char>((value >> 8) & 0xffu));
}

void put_u32(std::string& out, std::uint32_t value)
{
    out.push_back(static_cast<char>(value & 0xffu));
    out.push_back(static_cast<char>((value >> 8) & 0xffu));
    out.push_back(static_cast<char>((value >> 16) & 0xffu));
    out.push_back(static_cast<char>((value >> 24) & 0xffu));
}

void put_u64(std::string& out, std::uint64_t value)
{
    put_u32(out, static_cast<std::uint32_t>(value & 0xffffffffu));
    put_u32(out, static_cast<std::uint32_t>((value >> 32) & 0xffffffffu));
}

// What the end-of-central-directory record of a raw_zip() claims about the archive, which is what
// opening it costs and what the caps are checked against. A zero claims the truth.
struct Claims
{
    std::uint64_t entries = 0;         ///< Number of entries the record declares.
    std::uint64_t directory_bytes = 0; ///< Size of the central directory the record declares.
    std::string comment;               ///< Written after the record, as a zip comment is.
    bool zip64 = false;                ///< The numbers go into a zip64 record, the 16 and 32 bit
                                       ///< fields of the ordinary one being saturated.
};

// A zip of stored (or, where the test says so, deflated) entries, built from the three
// records of the format. Written here rather than through the Zipper so that the sizes in
// the central directory, which is all a reader of an archive looks at, are the ones the
// test means.
std::string raw_zip(const std::vector<RawEntry>& entries, const Claims& claims = {})
{
    std::string body, central;

    for (const RawEntry& entry : entries) {
        const std::uint32_t comp_size = static_cast<std::uint32_t>(entry.data.size());
        const std::uint32_t uncomp_size =
            entry.declared_uncomp_size != 0 ? entry.declared_uncomp_size : comp_size;
        const std::uint32_t crc = static_cast<std::uint32_t>(
            mz_crc32(MZ_CRC32_INIT, reinterpret_cast<const unsigned char*>(entry.data.data()), entry.data.size()));
        const std::uint32_t local_ofs = static_cast<std::uint32_t>(body.size());

        body += "PK\x03\x04";
        put_u16(body, 20); // version needed
        put_u16(body, 0);  // flags
        put_u16(body, entry.method);
        put_u16(body, 0); // time
        put_u16(body, 0); // date
        put_u32(body, crc);
        put_u32(body, comp_size);
        put_u32(body, uncomp_size);
        put_u16(body, static_cast<std::uint16_t>(entry.name.size()));
        put_u16(body, 0); // extra
        body += entry.name;
        body += entry.data;

        central += "PK\x01\x02";
        put_u16(central, 20); // version made by
        put_u16(central, 20); // version needed
        put_u16(central, 0);  // flags
        put_u16(central, entry.method);
        put_u16(central, 0); // time
        put_u16(central, 0); // date
        put_u32(central, crc);
        put_u32(central, comp_size);
        put_u32(central, uncomp_size);
        put_u16(central, static_cast<std::uint16_t>(entry.name.size()));
        put_u16(central, 0); // extra
        put_u16(central, 0); // comment
        put_u16(central, 0); // disk
        put_u16(central, 0); // internal attributes
        put_u32(central, 0); // external attributes
        put_u32(central, local_ofs);
        central += entry.name;
    }

    const std::uint64_t declared_entries = claims.entries != 0 ? claims.entries : entries.size();
    const std::uint64_t declared_bytes = claims.directory_bytes != 0 ? claims.directory_bytes : central.size();

    std::string out = body + central;
    if (claims.zip64) {
        // A zip64 end-of-central-directory record and the locator that points at it, which is the
        // only way an archive can declare more entries than the 16 bit field of the record holds.
        const std::uint64_t zip64_record_offset = static_cast<std::uint64_t>(out.size());
        out += "PK\x06\x06";
        put_u64(out, 44); // size of this record after these eight bytes
        put_u16(out, 45); // version made by
        put_u16(out, 45); // version needed
        put_u32(out, 0);  // this disk
        put_u32(out, 0);  // disk with the central directory
        put_u64(out, declared_entries);
        put_u64(out, declared_entries);
        put_u64(out, declared_bytes);
        put_u64(out, static_cast<std::uint64_t>(body.size()));
        out += "PK\x06\x07";
        put_u32(out, 0); // disk with the zip64 record
        put_u64(out, zip64_record_offset);
        put_u32(out, 1); // total number of disks
    }
    out += "PK\x05\x06";
    put_u16(out, 0); // this disk
    put_u16(out, 0); // disk with the central directory
    if (claims.zip64) {
        // Saturated, so the numbers are the ones of the zip64 record above.
        put_u16(out, 0xffff);
        put_u16(out, 0xffff);
        put_u32(out, 0xffffffffu);
        put_u32(out, 0xffffffffu);
    } else {
        put_u16(out, static_cast<std::uint16_t>(declared_entries));
        put_u16(out, static_cast<std::uint16_t>(declared_entries));
        put_u32(out, static_cast<std::uint32_t>(declared_bytes));
        put_u32(out, static_cast<std::uint32_t>(body.size()));
    }
    put_u16(out, static_cast<std::uint16_t>(claims.comment.size()));
    out += claims.comment;
    return out;
}

std::string read_head(const fs::path& path, std::size_t bytes = 4 * 1024)
{
    boost::filesystem::ifstream in{path, std::ios::binary};
    std::string                 head(bytes, '\0');
    in.read(head.data(), static_cast<std::streamsize>(bytes));
    head.resize(static_cast<std::size_t>(in.gcount()));
    return head;
}

ForeignResinProfile read_ok(const fs::path& path)
{
    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    const std::string              failure = result.has_value() ? "" : result.error();
    INFO(failure);
    REQUIRE(result.has_value());
    return *result;
}

/// The end-of-central-directory record of a zip built here, read the way the reader reads it off
/// the disk. The bytes are the whole file, which is what the tail of a small file is.
Slic3r::Biz::ZipDirectoryInfo directory_info_of(const std::string& zip)
{
    const std::optional<Slic3r::Biz::ZipDirectoryInfo> info = Slic3r::Biz::read_zip_directory_info(zip, zip.size());
    REQUIRE(info.has_value());
    REQUIRE(info->found);
    return *info;
}

double number(const std::optional<double>& value)
{
    REQUIRE(value.has_value());
    return *value;
}

} // namespace

TEST_CASE("SlicedArchiveResinReader - maps the material settings of a sliced archive", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile =
        read_ok(write_archive(dir.path() / "material.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));

    REQUIRE(profile.source_format == "sliced-archive");
    REQUIRE(number(profile.material.exposure_time_s) == Approx(2.5));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(30.));
    REQUIRE(number(profile.material.layer_height_mm) == Approx(0.05));
    REQUIRE(number(profile.material.initial_layer_height_mm) == Approx(0.2));
    REQUIRE(profile.material.faded_layer_count == 4);
    REQUIRE(profile.material.slow_layer_count == 2);
    REQUIRE(profile.material.fast_layer_count == 8);
    REQUIRE(profile.material.bottom_layer_count == 6);
    REQUIRE(profile.material.material_name == "Grey Resin");
    REQUIRE(profile.material.material_vendor == "Some Resin Co");
    REQUIRE(profile.printer_hint == "SL1");
    REQUIRE(profile.warnings.empty());
}

TEST_CASE("SlicedArchiveResinReader - every key of both ini files is kept", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile =
        read_ok(write_archive(dir.path() / "raw.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));

    // The two files name the same setting differently, and the mapper may want either.
    REQUIRE(profile.raw_values.at("expTime") == "2.5");
    REQUIRE(profile.raw_values.at("exposure_time") == "2.5");
    REQUIRE(profile.raw_values.at("numFade") == "4");
    REQUIRE(profile.raw_values.at("faded_layers") == "4");
    // Keys that are not a material setting stay in the map instead of being dropped.
    REQUIRE(profile.raw_values.at("printTime") == "3600");
    REQUIRE(profile.raw_values.at("display_width") == "144");
}

TEST_CASE("SlicedArchiveResinReader - the embedded profile wins over the printer config", "[resin_profile][sl1]")
{
    LocalDir dir;
    // A printer running one exposure time, sliced with another.
    const fs::path path = write_archive(dir.path() / "changed.sl1", {
        {"config.ini", "expTime = 2.5\nexpTimeFirst = 30\nlayerHeight = 0.05\nprinterModel = SL1\n"},
        {"prusaslicer.ini", "exposure_time = 3\ninitial_exposure_time = 40\nlayer_height = 0.05\n"},
    });

    const ForeignResinProfile profile = read_ok(path);

    REQUIRE(number(profile.material.exposure_time_s) == Approx(3.));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(40.));
    // Both spellings survive, so a review table can show where a value came from.
    REQUIRE(profile.raw_values.at("expTime") == "2.5");
    REQUIRE(profile.raw_values.at("exposure_time") == "3");
}

TEST_CASE("SlicedArchiveResinReader - a job without the embedded profile still reads", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile = read_ok(write_archive(dir.path() / "old.sl1", {{"config.ini", CONFIG_INI}}));

    // Older files have no prusaslicer.ini, so the settings come from config.ini alone.
    REQUIRE(number(profile.material.exposure_time_s) == Approx(2.5));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(30.));
    REQUIRE(number(profile.material.layer_height_mm) == Approx(0.05));
    REQUIRE(profile.material.material_name == "Grey Resin");
    REQUIRE_FALSE(profile.material.bottom_layer_count.has_value());
    REQUIRE_FALSE(profile.material.initial_layer_height_mm.has_value());
}

TEST_CASE("SlicedArchiveResinReader - numBottom of config.ini is a bottom layer count", "[resin_profile][sl1]")
{
    LocalDir dir;
    // A file of this fork's writer with no embedded profile: the printer config carries the
    // count, under the key the SL1 firmware has no name for.
    const std::string config_ini =
        "expTime = 2.5\n"
        "expTimeFirst = 30\n"
        "layerHeight = 0.05\n"
        "numBottom = 6\n"
        "numFade = 4\n";
    const ForeignResinProfile profile =
        read_ok(write_archive(dir.path() / "numbottom.sl1", {{"config.ini", config_ini}}));

    REQUIRE(profile.material.bottom_layer_count == 6);
    // numFade is the transition count, so the two keys stay two settings.
    REQUIRE(profile.material.faded_layer_count == 4);
    REQUIRE(profile.warnings.empty());
}

TEST_CASE("SlicedArchiveResinReader - a value that is not a number warns and is left empty", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile = read_ok(write_archive(dir.path() / "garbage.sl1",
                                                              {{"config.ini", "expTime = soon\nlayerHeight = 0.05\n"}}));

    REQUIRE_FALSE(profile.material.exposure_time_s.has_value());
    REQUIRE(profile.raw_values.at("expTime") == "soon");
    REQUIRE(profile.warnings.size() == 1);
    REQUIRE(profile.warnings.front().find("expTime") != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - an archive without any settings says so", "[resin_profile][sl1]")
{
    LocalDir dir;
    const fs::path path = write_archive(dir.path() / "empty.sl1", {{"job00000.png", "not really a png"}});

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
    REQUIRE(result.error().find("config.ini") != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - a file that is not a zip is an error, not a crash", "[resin_profile][sl1]")
{
    LocalDir dir;
    const fs::path path = dir.path() / "notazip.sl1";
    write_text(path, "not a zip file");

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
}

TEST_CASE("SlicedArchiveResinReader - sniff takes a zip that has a config.ini", "[resin_profile][sl1]")
{
    LocalDir dir;
    const SlicedArchiveResinReader reader;

    // The name of the first entry is inside the head the registry sniffs.
    REQUIRE(reader.sniff(read_head(
        write_archive(dir.path() / "sniff.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}))));
}

TEST_CASE("SlicedArchiveResinReader - sniff leaves what is not a sliced archive alone", "[resin_profile][sl1]")
{
    const SlicedArchiveResinReader reader;

    REQUIRE_FALSE(reader.sniff(""));
    REQUIRE_FALSE(reader.sniff("PK"));
    REQUIRE_FALSE(reader.sniff("expTime = 2.5\nlayerHeight = 0.05\n"));

    LocalDir   dir;
    const auto other = write_archive(dir.path() / "other.zip", {{"readme.txt", "no settings in here"}});
    // A zip is not enough: a .3mf or a .cfgx is one too, and its reader has to get a chance.
    REQUIRE_FALSE(reader.sniff(read_head(other)));
}

TEST_CASE("ResinProfileReaderRegistry - dispatches a .sl1 to the sliced archive reader", "[resin_profile][sl1]")
{
    ResinProfileReaderRegistry registry;
    register_resin_profile_readers(registry);

    LocalDir dir;
    const auto sl1 = registry.read_file(
        write_archive(dir.path() / "registered.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));
    REQUIRE(sl1.has_value());
    REQUIRE(sl1->source_format == "sliced-archive");
    REQUIRE(number(sl1->material.exposure_time_s) == Approx(2.5));

    // The Chitubox reader is still reached, and still claims a .cfg.
    const fs::path cfg = dir.path() / "resin.cfg";
    write_text(cfg, "normalExposureTime:2.5\nlayerHeight:0.05\n");

    const auto chitubox = registry.read_file(cfg);
    REQUIRE(chitubox.has_value());
    REQUIRE(chitubox->source_format == "chitubox-cfg");
}

TEST_CASE("SlicedArchiveResinReader - a job of many layers is read from its config.ini alone", "[resin_profile][sl1]")
{
    LocalDir dir;

    // What a real job is: a small config.ini next to tens of megabytes of layer images. The
    // padding stands in for the layers and is stored, so the archive on disk is as big as
    // the one a real print writes, which is the case the registry used to refuse outright.
    const std::string layers(20 * 1024 * 1024, 'x');
    const fs::path    path = write_archive(
        dir.path() / "big.sl1", {{"config.ini", CONFIG_INI}, {"job00000.png", layers}},
        Slic3r::Biz::PrintHost::Sla::Zipper::NO_COMPRESSION);
    REQUIRE(fs::file_size(path) > static_cast<std::uintmax_t>(ResinProfileReaderRegistry::MAX_FILE_SIZE));

    // The registry hands a container to the reader that opens it, whatever the file weighs,
    // and the reader never extracts the layer image.
    ResinProfileReaderRegistry registry;
    register_resin_profile_readers(registry);
    const auto                 result = registry.read_file(path);
    const std::string          failure = result.has_value() ? "" : result.error();
    INFO(failure);
    REQUIRE(result.has_value());
    REQUIRE(result->source_format == "sliced-archive");
    REQUIRE(number(result->material.exposure_time_s) == Approx(2.5));
    REQUIRE(number(result->material.initial_exposure_time_s) == Approx(30.));
    REQUIRE(result->material.material_name == "Grey Resin");
}

TEST_CASE("SlicedArchiveResinReader - an ini entry over the cap is refused", "[resin_profile][sl1]")
{
    LocalDir dir;

    // One byte over the cap, and all of it in the value of the first key: the ceiling is on
    // the size of the entry, not on how many keys it holds. The archive itself stays small
    // on disk, since the entry is compressed, which is the point of checking the size the
    // central directory declares.
    std::string huge = "expTime = 2.5\n";
    huge.append(SlicedArchiveResinReader::MAX_INI_ENTRY_SIZE + 1, 'x');
    const fs::path path = write_archive(dir.path() / "huge-ini.sl1", {{"config.ini", huge}});

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
    // The error says which entry, how big it claims to be and what is read, so that the
    // user can tell this file apart from one that is merely too big to read at all.
    REQUIRE(result.error().find("config.ini") != std::string::npos);
    REQUIRE(result.error().find(std::to_string(huge.size())) != std::string::npos);
    REQUIRE(result.error().find(std::to_string(SlicedArchiveResinReader::MAX_INI_ENTRY_SIZE)) != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - an entry that claims to be huge is refused, not allocated", "[resin_profile][sl1]")
{
    LocalDir dir;

    // A zip bomb is an archive that promises far more than it holds. Without the cap the
    // reader would ask for the size the entry claims, so this archive is written byte by
    // byte: 15 bytes of ini text, 3.75 GB of promise in the central directory. Deflated,
    // because a stored entry whose two sizes differ is not a valid record at all.
    const std::uint32_t promised = 0xf0000000u;
    const fs::path      path     = dir.path() / "bomb.sl1";
    write_text(path, raw_zip({{"config.ini", "expTime = 2.5\n", promised, 8}}));

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
    REQUIRE(result.error().find("config.ini") != std::string::npos);
    REQUIRE(result.error().find(std::to_string(promised)) != std::string::npos);
    REQUIRE(result.error().find(std::to_string(SlicedArchiveResinReader::MAX_INI_ENTRY_SIZE)) != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - an archive with more entries than are scanned is refused", "[resin_profile][sl1]")
{
    LocalDir dir;

    // A job has one entry per layer, so a real one stays far below the cap. A zip whose
    // central directory names hundreds of thousands of entries is not a sliced job, and it
    // must not keep the reader walking through it.
    const fs::path path = dir.path() / "many.sl1";
    {
        Slic3r::Biz::PrintHost::Sla::Zipper zipper{path.string()};
        for (unsigned i = 0; i <= SlicedArchiveResinReader::MAX_ENTRIES_SCANNED; ++i)
            zipper.add_entry("job" + std::to_string(i) + ".png", "x", 1);
        zipper.add_entry("config.ini", CONFIG_INI.data(), CONFIG_INI.size());
        zipper.finalize();
    }

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
    REQUIRE(result.error().find("config.ini") == std::string::npos);
    REQUIRE(result.error().find("entries") != std::string::npos);
}

TEST_CASE(
    "read_zip_directory_info - what the end of the file says the archive costs",
    "[resin_profile][sl1]"
)
{
    SECTION("a plain record of two entries")
    {
        const std::vector<RawEntry> entries{{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}};
        const Slic3r::Biz::ZipDirectoryInfo info = directory_info_of(raw_zip(entries));

        CHECK(info.entries == 2);
        CHECK(info.directory_bytes > 0);
        CHECK(info.directory_offset > 0);
    }

    SECTION("a comment does not hide the record, and a signature inside one is not the record")
    {
        // The signature of the record inside the comment is the trap: it is nearer the end of the
        // file than the record itself, and taking it for the record would report whatever the bytes
        // after it happen to say. Two entries are declared and two are there, so the count comes
        // from the record.
        Claims claims;
        claims.comment = std::string("a comment with a PK\x05\x06 in it, and more text after that");
        const std::vector<RawEntry> entries{{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}};
        const Slic3r::Biz::ZipDirectoryInfo info = directory_info_of(raw_zip(entries, claims));

        CHECK(info.entries == 2);
    }

    SECTION("a zip64 record is followed when the ordinary one is saturated")
    {
        Claims claims;
        claims.zip64           = true;
        claims.entries         = 200000;
        claims.directory_bytes = 30000000;
        const std::vector<RawEntry> entries{{"config.ini", CONFIG_INI}};
        const Slic3r::Biz::ZipDirectoryInfo info = directory_info_of(raw_zip(entries, claims));

        CHECK(info.entries == 200000);
        CHECK(info.directory_bytes == 30000000);
    }

    SECTION("a file that is not a zip at all has no record in it")
    {
        const std::string text = "not a zip file, just some text";
        CHECK_FALSE(Slic3r::Biz::read_zip_directory_info(text, text.size()).has_value());
        CHECK_FALSE(Slic3r::Biz::read_zip_directory_info("", 0).has_value());
    }
}

TEST_CASE(
    "SlicedArchiveResinReader - an archive over the caps is refused before it is opened",
    "[resin_profile][sl1]"
)
{
    LocalDir dir;
    const SlicedArchiveResinReader reader;

    SECTION("more entries than the cap, in an archive of one")
    {
        // The promise is in the record, not in the file: one entry on disk, half a million declared,
        // which is the number miniz would size its index from.
        Claims claims;
        claims.entries = 500000;
        const fs::path path = dir.path() / "too-many.sl1";
        write_text(path, raw_zip({{"config.ini", CONFIG_INI}}, claims));

        const SlicedArchiveResinReader reader;
        const auto                     result = reader.read(path);
        REQUIRE_FALSE(result.has_value());
        // The error names the file, the count and the cap, so this is told apart from a file that is
        // merely not a zip.
        REQUIRE(result.error().find("too-many.sl1") != std::string::npos);
        REQUIRE(result.error().find("entries") != std::string::npos);
        REQUIRE(result.error().find("500000") != std::string::npos);
        REQUIRE(result.error().find(std::to_string(SlicedArchiveResinReader::MAX_ENTRIES_SCANNED))
                != std::string::npos);
        // The file is still a sliced archive as far as the format goes, so the registry hands it to
        // this reader and the user is told what was wrong with it instead of that nothing here
        // recognises it. The archive itself is never opened.
        REQUIRE(reader.sniff_path(path));
        ResinProfileReaderRegistry registry;
        register_resin_profile_readers(registry);
        const auto                 through_registry = registry.read_file(path);
        REQUIRE_FALSE(through_registry.has_value());
        REQUIRE(through_registry.error().find("500000") != std::string::npos);
    }

    SECTION("a central directory over the cap, in an archive of one")
    {
        Claims claims;
        claims.directory_bytes = 3ull * 1024 * 1024 * 1024;
        const fs::path path = dir.path() / "huge-directory.sl1";
        write_text(path, raw_zip({{"config.ini", CONFIG_INI}}, claims));

        const SlicedArchiveResinReader reader;
        const auto                     result = reader.read(path);
        REQUIRE_FALSE(result.has_value());
        REQUIRE(result.error().find("huge-directory.sl1") != std::string::npos);
        REQUIRE(result.error().find("central directory") != std::string::npos);
        REQUIRE(result.error().find("3221225472") != std::string::npos);
        REQUIRE(result.error().find(std::to_string(SlicedArchiveResinReader::MAX_CENTRAL_DIRECTORY_SIZE))
                != std::string::npos);
    }

    SECTION("the same promise in a zip64 record, which is the only way to make one that big")
    {
        Claims claims;
        claims.zip64  = true;
        claims.entries = 200000;
        const fs::path path = dir.path() / "too-many-zip64.sl1";
        write_text(path, raw_zip({{"config.ini", CONFIG_INI}}, claims));

        const auto result = reader.read(path);
        REQUIRE_FALSE(result.has_value());
        REQUIRE(result.error().find("200000") != std::string::npos);
    }

    SECTION("an archive within the caps is opened as before")
    {
        Claims claims;
        claims.comment = "written by a slicer";
        const fs::path path = dir.path() / "with-comment.sl1";
        write_text(path, raw_zip({{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}, claims));

        // A comment after the record is what a real archive can have, and the record is still found
        // in it, so the file is not refused for a shape it is allowed to have.
        REQUIRE(reader.sniff_path(path));
        const ForeignResinProfile profile = read_ok(path);
        CHECK(number(profile.material.exposure_time_s) == Approx(2.5));
    }
}
