#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "Slic3r/Biz/ResinProfile/ChituboxCfgReader.hpp"
#include "Slic3r/Biz/ResinProfile/ResinProfileReaderRegistry.hpp"
#include "Slic3r/Biz/ResinProfile/SlicedArchiveResinReader.hpp"
#include "Slic3r/Biz/ResultExport/SLA/Zipper.hpp"

#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>

#include <cstddef>
#include <map>
#include <optional>
#include <string>

using namespace Slic3r::Biz::ResinProfile;

using Catch::Approx;

namespace fs = boost::filesystem;

namespace {

// The metadata of a job as the archive writer puts it in config.ini. Hand written, so that
// the test does not depend on what a slicing run happens to produce.
const std::string CONFIG_INI =
    "# generated by a slicer\n"
    "version = 1\n"
    "expTime = 2.5\n"
    "expTimeFirst = 30\n"
    "expUserProfile = 2\n"
    "layerHeight = 0.05\n"
    "numFade = 4\n"
    "numSlow = 2\n"
    "numFast = 8\n"
    "materialName = Grey Resin\n"
    "materialVendor = Some Resin Co\n"
    "printerModel = SL1\n"
    "printerVariant = 1.7\n"
    "printTime = 3600\n"
    "usedMaterial = 1.5\n";

// The profile of the same job, as it is embedded in prusaslicer.ini. It names the very same
// settings differently, which is what the reader has to resolve.
const std::string PROFILE_INI =
    "exposure_time = 2.5\n"
    "initial_exposure_time = 30\n"
    "layer_height = 0.05\n"
    "initial_layer_height = 0.2\n"
    "faded_layers = 4\n"
    "bottom_layer_count = 6\n"
    "sla_material_settings_id = Grey Resin\n"
    "material_vendor = Some Resin Co\n"
    "display_width = 144\n"
    "display_pixels_x = 1440\n";

// The fixture archives are built under the working directory of the test run, so a test
// leaves nothing behind outside the build tree.
class LocalDir
{
public:
    LocalDir()
        : m_path{fs::current_path() / "sliced-archive-resin-reader-tests"}
    {
        boost::system::error_code ec;
        fs::create_directories(m_path, ec);
    }

    ~LocalDir()
    {
        boost::system::error_code ec;
        fs::remove_all(m_path, ec);
    }

    LocalDir(const LocalDir&)            = delete;
    LocalDir& operator=(const LocalDir&) = delete;

    const fs::path& path() const { return m_path; }

private:
    fs::path m_path;
};

void write_text(const fs::path& path, const std::string& contents)
{
    boost::filesystem::ofstream out{path, std::ios::binary};
    out << contents;
}

fs::path write_archive(const fs::path& path, const std::map<std::string, std::string>& entries)
{
    Slic3r::Biz::PrintHost::Sla::Zipper zipper{path.string()};
    for (const auto& [name, data] : entries)
        zipper.add_entry(name, data.data(), data.size());
    zipper.finalize();
    return path;
}

std::string read_head(const fs::path& path, std::size_t bytes = 4 * 1024)
{
    boost::filesystem::ifstream in{path, std::ios::binary};
    std::string                 head(bytes, '\0');
    in.read(head.data(), static_cast<std::streamsize>(bytes));
    head.resize(static_cast<std::size_t>(in.gcount()));
    return head;
}

ForeignResinProfile read_ok(const fs::path& path)
{
    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    const std::string              failure = result.has_value() ? "" : result.error();
    INFO(failure);
    REQUIRE(result.has_value());
    return *result;
}

double number(const std::optional<double>& value)
{
    REQUIRE(value.has_value());
    return *value;
}

} // namespace

TEST_CASE("SlicedArchiveResinReader - maps the material settings of a sliced archive", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile =
        read_ok(write_archive(dir.path() / "material.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));

    REQUIRE(profile.source_format == "sliced-archive");
    REQUIRE(number(profile.material.exposure_time_s) == Approx(2.5));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(30.));
    REQUIRE(number(profile.material.layer_height_mm) == Approx(0.05));
    REQUIRE(number(profile.material.initial_layer_height_mm) == Approx(0.2));
    REQUIRE(profile.material.faded_layer_count == 4);
    REQUIRE(profile.material.slow_layer_count == 2);
    REQUIRE(profile.material.fast_layer_count == 8);
    REQUIRE(profile.material.bottom_layer_count == 6);
    REQUIRE(profile.material.material_name == "Grey Resin");
    REQUIRE(profile.material.material_vendor == "Some Resin Co");
    REQUIRE(profile.printer_hint == "SL1");
    REQUIRE(profile.warnings.empty());
}

TEST_CASE("SlicedArchiveResinReader - every key of both ini files is kept", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile =
        read_ok(write_archive(dir.path() / "raw.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));

    // The two files name the same setting differently, and the mapper may want either.
    REQUIRE(profile.raw_values.at("expTime") == "2.5");
    REQUIRE(profile.raw_values.at("exposure_time") == "2.5");
    REQUIRE(profile.raw_values.at("numFade") == "4");
    REQUIRE(profile.raw_values.at("faded_layers") == "4");
    // Keys that are not a material setting stay in the map instead of being dropped.
    REQUIRE(profile.raw_values.at("printTime") == "3600");
    REQUIRE(profile.raw_values.at("display_width") == "144");
}

TEST_CASE("SlicedArchiveResinReader - the embedded profile wins over the printer config", "[resin_profile][sl1]")
{
    LocalDir dir;
    // A printer running one exposure time, sliced with another.
    const fs::path path = write_archive(dir.path() / "changed.sl1", {
        {"config.ini", "expTime = 2.5\nexpTimeFirst = 30\nlayerHeight = 0.05\nprinterModel = SL1\n"},
        {"prusaslicer.ini", "exposure_time = 3\ninitial_exposure_time = 40\nlayer_height = 0.05\n"},
    });

    const ForeignResinProfile profile = read_ok(path);

    REQUIRE(number(profile.material.exposure_time_s) == Approx(3.));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(40.));
    // Both spellings survive, so a review table can show where a value came from.
    REQUIRE(profile.raw_values.at("expTime") == "2.5");
    REQUIRE(profile.raw_values.at("exposure_time") == "3");
}

TEST_CASE("SlicedArchiveResinReader - a job without the embedded profile still reads", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile = read_ok(write_archive(dir.path() / "old.sl1", {{"config.ini", CONFIG_INI}}));

    // Older files have no prusaslicer.ini, so the settings come from config.ini alone.
    REQUIRE(number(profile.material.exposure_time_s) == Approx(2.5));
    REQUIRE(number(profile.material.initial_exposure_time_s) == Approx(30.));
    REQUIRE(number(profile.material.layer_height_mm) == Approx(0.05));
    REQUIRE(profile.material.material_name == "Grey Resin");
    REQUIRE_FALSE(profile.material.bottom_layer_count.has_value());
    REQUIRE_FALSE(profile.material.initial_layer_height_mm.has_value());
}

TEST_CASE("SlicedArchiveResinReader - a value that is not a number warns and is left empty", "[resin_profile][sl1]")
{
    LocalDir dir;
    const ForeignResinProfile profile = read_ok(write_archive(dir.path() / "garbage.sl1",
                                                              {{"config.ini", "expTime = soon\nlayerHeight = 0.05\n"}}));

    REQUIRE_FALSE(profile.material.exposure_time_s.has_value());
    REQUIRE(profile.raw_values.at("expTime") == "soon");
    REQUIRE(profile.warnings.size() == 1);
    REQUIRE(profile.warnings.front().find("expTime") != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - an archive without any settings says so", "[resin_profile][sl1]")
{
    LocalDir dir;
    const fs::path path = write_archive(dir.path() / "empty.sl1", {{"job00000.png", "not really a png"}});

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
    REQUIRE(result.error().find("config.ini") != std::string::npos);
}

TEST_CASE("SlicedArchiveResinReader - a file that is not a zip is an error, not a crash", "[resin_profile][sl1]")
{
    LocalDir dir;
    const fs::path path = dir.path() / "notazip.sl1";
    write_text(path, "not a zip file");

    const SlicedArchiveResinReader reader;
    const auto                     result = reader.read(path);
    REQUIRE_FALSE(result.has_value());
}

TEST_CASE("SlicedArchiveResinReader - sniff takes a zip that has a config.ini", "[resin_profile][sl1]")
{
    LocalDir dir;
    const SlicedArchiveResinReader reader;

    // The name of the first entry is inside the head the registry sniffs.
    REQUIRE(reader.sniff(read_head(
        write_archive(dir.path() / "sniff.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}))));
}

TEST_CASE("SlicedArchiveResinReader - sniff leaves what is not a sliced archive alone", "[resin_profile][sl1]")
{
    const SlicedArchiveResinReader reader;

    REQUIRE_FALSE(reader.sniff(""));
    REQUIRE_FALSE(reader.sniff("PK"));
    REQUIRE_FALSE(reader.sniff("expTime = 2.5\nlayerHeight = 0.05\n"));

    LocalDir   dir;
    const auto other = write_archive(dir.path() / "other.zip", {{"readme.txt", "no settings in here"}});
    // A zip is not enough: a .3mf or a .cfgx is one too, and its reader has to get a chance.
    REQUIRE_FALSE(reader.sniff(read_head(other)));
}

TEST_CASE("ResinProfileReaderRegistry - dispatches a .sl1 to the sliced archive reader", "[resin_profile][sl1]")
{
    ResinProfileReaderRegistry registry;
    register_resin_profile_readers(registry);

    LocalDir dir;
    const auto sl1 = registry.read_file(
        write_archive(dir.path() / "registered.sl1", {{"config.ini", CONFIG_INI}, {"prusaslicer.ini", PROFILE_INI}}));
    REQUIRE(sl1.has_value());
    REQUIRE(sl1->source_format == "sliced-archive");
    REQUIRE(number(sl1->material.exposure_time_s) == Approx(2.5));

    // The Chitubox reader is still reached, and still claims a .cfg.
    const fs::path cfg = dir.path() / "resin.cfg";
    write_text(cfg, "normalExposureTime:2.5\nlayerHeight:0.05\n");

    const auto chitubox = registry.read_file(cfg);
    REQUIRE(chitubox.has_value());
    REQUIRE(chitubox->source_format == "chitubox-cfg");
}
