#pragma once

#include "Slic3r/Domain/ModelObject.hpp"
#include "Slic3r/Domain/SLA/SupportPoint.hpp"

namespace Slic3r::App::Plater {

/// Whether leaving the support points tool writes the points a generation produced on the model they
/// were made for (M2.31). The tool kept those points to itself until Apply was pressed, so closing
/// the tool used to throw them away silently and the model fell back onto the plate: the preview
/// service has nothing to draw without points on the ModelObject, and the slice finds none either.
/// Leaving the tool therefore applies what is waiting, exactly as Apply does, undo snapshot included.
///
/// Nothing is written when no generation has produced points yet or when a generation is still
/// running: its result is dropped with the job.
///
/// @p discard_requested is the Discard button, the one way to throw the points away: it clears them
/// before it closes the tool, so the tool finds nothing left to apply.
bool apply_generated_points_on_leaving(bool has_generated_points, bool discard_requested);

/// Writes the points a generation produced on @p model_object, with the status AutoGenerated. This
/// is the one write of generated points, so the Apply button, leaving the tool and Auto support all
/// put the same points with the same status on a model.
void apply_generated_support_points(
    Domain::ModelObject& model_object,
    Domain::SLA::SupportPoints points
);

} // namespace Slic3r::App::Plater
