// M2.32: removing the support points of a model without opening the support points tool. The three
// actions that do it (the Preview sidebar's "Clear selected" / "Clear all", the tool's "Remove all
// points" and the object context menu) all go through the two functions of
// SlaSupportPointsClear.hpp, so the tests below play their parts: work out what would go, then take
// it away through SceneInteractor::modify_sla_support_points under one undo snapshot.
#include <catch2/catch_test_macros.hpp>

#include <cstddef>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "Slic3r/App/Plater/ThumbnailImageGenerator.hpp"
#include "Slic3r/App/Platform/StdMainThreadDispatcher.hpp"
#include "Slic3r/App/Plater/SlaSupportPointsClear.hpp"
#include "Slic3r/App/Undo/ModelSerialize.hpp"
#include "Slic3r/Biz/Algorithms/TriangleMesh.hpp"
#include "Slic3r/Biz/IUndoProvider.hpp"
#include "Slic3r/Biz/ProjectInteractor.hpp"
#include "Slic3r/Biz/Scene/SceneInteractor.hpp"
#include "Slic3r/Biz/Scene/Selection.hpp"
#include "Slic3r/Directories.hpp"
#include "Slic3r/Domain/Model.hpp"
#include "Slic3r/Domain/ModelObject.hpp"
#include "Slic3r/Domain/Project.hpp"
#include "Slic3r/Domain/SLA/SupportPoint.hpp"
#include "Slic3r/Domain/TriangleMesh.hpp"
#include "Slic3r/Domain/Workbench.hpp"
#include "Slic3r/TestUtils/AppInstanceMessageHandlerScope.hpp"
#include "Slic3r/TestUtils/JobManagerScope.hpp"
#include "Slic3r/TestUtils/ScopedThreadDispatcher.hpp"
#include "Slic3r/TestUtils/TestData.hpp"

using Slic3r::App::Plater::clear_sla_support_points;
using Slic3r::App::Plater::sla_support_points_clear_plan;
using Slic3r::App::Plater::sla_support_points_clear_question;
using Slic3r::App::Plater::SlaSupportPointsClearPlan;
using Slic3r::App::Undo::load_serialized_model;
using Slic3r::App::Undo::serialize_model;
using Slic3r::App::Undo::SerializedData;
using Slic3r::Biz::ProjectInteractor;
using Slic3r::Biz::UndoSnapshotSelection;
using Slic3r::Biz::UndoSnapshotType;
using Slic3r::Domain::ElementRef;
using Slic3r::Domain::Model;
using Slic3r::Domain::ModelObject;
using Slic3r::Domain::Project;
using Slic3r::Domain::Vec3f;
using Slic3r::Domain::SLA::PointsStatus;
using Slic3r::Domain::SLA::SupportPoint;
using Slic3r::Domain::SLA::SupportPoints;
using Slic3r::Domain::SLA::SupportPointType;

namespace TriMesh = Slic3r::Biz::Algorithms::TriangleMesh;

namespace {

SupportPoints make_points(std::size_t count)
{
    SupportPoints points;
    points.reserve(count);
    for (std::size_t i = 0; i < count; ++i) {
        points.push_back(SupportPoint{Vec3f{float(i), 1.f, 2.f}, 0.4f, SupportPointType::slope});
    }
    return points;
}

/// A model of @p count points, of the status a generation leaves behind.
ModelObject*
add_object(Model& model, std::size_t count, PointsStatus status = PointsStatus::AutoGenerated)
{
    ModelObject* object        = model.add_object();
    object->name               = "object";
    object->sla_support_points = make_points(count);
    object->sla_points_status  = status;
    return object;
}

std::size_t point_count(const ModelObject* object)
{
    return object == nullptr ? 0 : object->sla_support_points.size();
}

} // namespace

TEST_CASE(
    "sla_support_points_clear_plan - what the action would do",
    "[SlaSupportPointsClear][M2.32]"
)
{
    SECTION("an empty list removes nothing and asks nothing")
    {
        const auto plan = sla_support_points_clear_plan({});

        CHECK(plan.empty());
        CHECK(plan.object_refs.empty());
        CHECK(plan.point_count == 0);
        CHECK(sla_support_points_clear_question(plan).empty());
    }

    SECTION("a model without points is not part of the action")
    {
        Model model;
        add_object(model, 0, PointsStatus::NoPoints);
        add_object(model, 3);

        const auto plan = sla_support_points_clear_plan({model.objects[0], model.objects[1]});

        REQUIRE(plan.object_refs.size() == 1);
        CHECK(plan.object_refs.front().object_id == model.objects[1]->id().id);
        CHECK(plan.point_count == 3);
    }

    SECTION("every model with points is, and their points add up")
    {
        Model model;
        add_object(model, 2);
        add_object(model, 0, PointsStatus::NoPoints);
        add_object(model, 5, PointsStatus::UserModified);

        const std::vector<const ModelObject*>
            models{model.objects[0], model.objects[1], model.objects[2]};
        const auto plan = sla_support_points_clear_plan(models);

        REQUIRE(plan.object_refs.size() == 2);
        CHECK(plan.object_refs.front().object_id == model.objects[0]->id().id);
        CHECK(plan.object_refs.back().object_id == model.objects[2]->id().id);
        CHECK(plan.point_count == 7);
    }

    SECTION("a model that is not there is skipped instead of ending the action")
    {
        Model model;
        add_object(model, 4);

        const auto plan = sla_support_points_clear_plan({nullptr, model.objects[0]});

        REQUIRE(plan.object_refs.size() == 1);
        CHECK(plan.point_count == 4);
    }
}

TEST_CASE(
    "sla_support_points_clear_question - what the user is asked",
    "[SlaSupportPointsClear][M2.32]"
)
{
    Model model;
    add_object(model, 12);

    SECTION("one model names its points")
    {
        const auto plan            = sla_support_points_clear_plan({model.objects[0]});
        const std::string question = sla_support_points_clear_question(plan);

        CHECK_FALSE(question.empty());
        CHECK(question.find("12") != std::string::npos);
        CHECK(question.find("model") != std::string::npos);
    }

    SECTION("more models name both counts")
    {
        add_object(model, 8);
        const std::vector<const ModelObject*> models{model.objects[0], model.objects[1]};
        const auto plan            = sla_support_points_clear_plan(models);
        const std::string question = sla_support_points_clear_question(plan);

        CHECK_FALSE(question.empty());
        CHECK(question.find("20") != std::string::npos);
        CHECK(question.find("2") != std::string::npos);
    }
}

/// The undo stack of this app keeps whole models, so what one undo brings back is what
/// serialize_model / load_serialized_model carry. The provider below records the snapshot of every
/// action the way the real one takes it, and can load an earlier one back into the project, which is
/// what one undo of a clear does.
struct ModelUndoProvider : Slic3r::Biz::IUndoProvider
{
    explicit ModelUndoProvider(ProjectInteractor& project_interactor) :
        m_project_interactor(project_interactor)
    {}

    void take_snapshot(UndoSnapshotType type) override
    {
        types.push_back(type);
        SerializedData previous;
        snapshots.push_back(
            serialize_model(m_project_interactor.selected_project().model(), previous)
        );
    }

    void select_snapshot(UndoSnapshotSelection::Variant /*snapshot_variant*/) override {}

    bool is_undo_possible() const override
    {
        return snapshots.size() > 1;
    }

    bool is_redo_possible() const override
    {
        return false;
    }

    /// One undo: the first snapshot of the run, loaded the way the undo of the app loads it.
    void undo()
    {
        REQUIRE(snapshots.size() > 1);
        Domain::Model model = load_serialized_model(snapshots.front());
        model.update_links_bottom_up_recursive();
        m_project_interactor.scene_interactor().set_state(
            m_project_interactor.selected_project_id(),
            std::move(model),
            Biz::Scene::ObjectSelection{}
        );
    }

    std::vector<UndoSnapshotType> types;
    std::vector<SerializedData> snapshots;

private:
    ProjectInteractor& m_project_interactor;
};

struct ClearFixture
{
    ClearFixture()
    {
        Slic3r::set_data_dir(Tests::get_datadir().string());

        project_interactor.preset_interactor().load_preset_bundle(
            Slic3r::Biz::Preset::IO::BundlePaths::make_test_runtime(Tests::get_datadir())
        );
        project_interactor.new_project();

        undo_provider_storage = std::make_unique<ModelUndoProvider>(project_interactor);
        undo_provider         = undo_provider_storage.get();
        project_interactor.set_undo_provider(std::move(undo_provider_storage));
    }

    /// Puts a model on the first build plate, as the actions find them there.
    ModelObject* place_model_with_points(std::size_t count)
    {
        Project& project = project_interactor.selected_project();
        scene_interactor.new_object_from_mesh(
            Slic3r::Domain::TriangleMesh{TriMesh::make_cube(20., 20., 20.)}
        );
        ModelObject* object        = project.model().objects.back();
        object->sla_support_points = make_points(count);
        object->sla_points_status =
            count > 0 ? PointsStatus::AutoGenerated : PointsStatus::NoPoints;
        return object;
    }

    Slic3r::Domain::Workbench workbench;
    Slic3r::App::Platform::StdMainThreadDispatcher dispatcher;
    Tests::AppInstanceMessageHandlerScope app_instance_message_handler_scope{dispatcher};
    Tests::JobManagerScope job_manager_scope{dispatcher};
    Slic3r::App::Plater::ThumbnailImageGenerator thumbnail_image_generator;
    ProjectInteractor project_interactor{workbench, dispatcher, thumbnail_image_generator};
    Slic3r::Biz::Scene::SceneInteractor& scene_interactor{project_interactor.scene_interactor()};
    Tests::ScopedThreadDispatcher thread_dispatcher{dispatcher};
    // The provider is owned by the interactor; the test only reads what it recorded.
    std::unique_ptr<ModelUndoProvider> undo_provider_storage;
    ModelUndoProvider* undo_provider{nullptr};
};

TEST_CASE_METHOD(
    ClearFixture,
    "clear_sla_support_points takes the points away in one snapshot",
    "[SlaSupportPointsClear][M2.32]"
)
{
    ModelObject* first     = place_model_with_points(3);
    ModelObject* second    = place_model_with_points(5);
    const size_t first_id  = first->id().id;
    const size_t second_id = second->id().id;

    const auto plan = sla_support_points_clear_plan(
        std::vector<const ModelObject*>{
            project_interactor.selected_project().find_object_by_id(first_id),
            project_interactor.selected_project().find_object_by_id(second_id)
        }
    );
    REQUIRE(plan.point_count == 8);

    const size_t taken = clear_sla_support_points(project_interactor, plan);

    Project& project            = project_interactor.selected_project();
    ModelObject* cleared_first  = project.find_object_by_id(first_id);
    ModelObject* cleared_second = project.find_object_by_id(second_id);

    CHECK(taken == 2);
    CHECK(point_count(cleared_first) == 0);
    CHECK(point_count(cleared_second) == 0);
    // NoPoints is what the M2.21 support preview watches for, so the tree and the lift go with it.
    CHECK(cleared_first->sla_points_status == PointsStatus::NoPoints);
    CHECK(cleared_second->sla_points_status == PointsStatus::NoPoints);

    // One undo snapshot for the whole action, and it is the clear one.
    REQUIRE(undo_provider->types.size() == 1);
    CHECK(undo_provider->types.front() == UndoSnapshotType::SlaSupportPointsClear);
}

TEST_CASE_METHOD(
    ClearFixture,
    "clear_sla_support_points leaves a model without points alone",
    "[SlaSupportPointsClear][M2.32]"
)
{
    ModelObject* with_points    = place_model_with_points(4);
    ModelObject* without_points = place_model_with_points(0);
    const size_t with_id        = with_points->id().id;
    const size_t without_id     = without_points->id().id;

    const auto plan = sla_support_points_clear_plan(
        std::vector<const ModelObject*>{
            project_interactor.selected_project().find_object_by_id(with_id),
            project_interactor.selected_project().find_object_by_id(without_id)
        }
    );
    // Only the model that has points is part of the action, and nothing was asked for it.
    REQUIRE(plan.object_refs.size() == 1);
    CHECK(plan.point_count == 4);

    clear_sla_support_points(project_interactor, plan);

    Project& project             = project_interactor.selected_project();
    ModelObject* cleared_with    = project.find_object_by_id(with_id);
    ModelObject* untouched_model = project.find_object_by_id(without_id);

    CHECK(point_count(cleared_with) == 0);
    CHECK(cleared_with->sla_points_status == PointsStatus::NoPoints);
    CHECK(point_count(untouched_model) == 0);
    CHECK(untouched_model->sla_points_status == PointsStatus::NoPoints);
    CHECK(untouched_model->instances.size() == 1);
    // One snapshot, and it covers one model: the model with no points was never written.
    REQUIRE(undo_provider->types.size() == 1);
}

TEST_CASE_METHOD(
    ClearFixture,
    "one undo brings the cleared points back",
    "[SlaSupportPointsClear][M2.32]"
)
{
    ModelObject* model         = place_model_with_points(6);
    const size_t object_id     = model->id().id;
    const SupportPoints before = model->sla_support_points;

    // The snapshot of the state the points are cleared from, the one an undo of the action reads.
    undo_provider->take_snapshot(UndoSnapshotType::InitializeProject);

    const auto plan = sla_support_points_clear_plan(
        std::vector<
            const ModelObject*>{project_interactor.selected_project().find_object_by_id(object_id)}
    );
    clear_sla_support_points(project_interactor, plan);
    REQUIRE(undo_provider->snapshots.size() == 2);

    Project& project = project_interactor.selected_project();
    REQUIRE(point_count(project.find_object_by_id(object_id)) == 0);

    undo_provider->undo();

    const ModelObject* undone = project.find_object_by_id(object_id);
    REQUIRE(point_count(undone) == before.size());
    CHECK(undone->sla_points_status == PointsStatus::AutoGenerated);
    for (std::size_t i = 0; i < before.size(); ++i) {
        CHECK(undone->sla_support_points[i].pos == before[i].pos);
        CHECK(undone->sla_support_points[i].type == before[i].type);
    }
}

TEST_CASE_METHOD(
    ClearFixture,
    "an empty plan asks nothing and takes nothing",
    "[SlaSupportPointsClear][M2.32]"
)
{
    place_model_with_points(0);

    const auto plan = sla_support_points_clear_plan({});
    REQUIRE(plan.empty());

    CHECK(clear_sla_support_points(project_interactor, plan) == 0);
    CHECK(undo_provider->types.empty());
}
