#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include "Slic3r/App/Plater/SlaSupportPointsEditing.hpp"
#include "Slic3r/App/Plater/SlaSupportPointsLeaving.hpp"
#include "Slic3r/App/Plater/SlaSupportPointsLift.hpp"
#include "Slic3r/App/Plater/SlaSupportPointsSettings.hpp"
#include "Slic3r/App/Scene/Ray.hpp"
#include "Slic3r/Biz/Algorithms/AABBMesh.hpp"
#include "Slic3r/Biz/Algorithms/TriangleMesh.hpp"
#include "Slic3r/Biz/Utils/MeshRaycaster.hpp"
#include "Slic3r/Domain/Model.hpp"
#include "Slic3r/Domain/ModelObject.hpp"
#include "Slic3r/Domain/SLA/SupportPoint.hpp"
#include "Slic3r/Domain/Types.hpp"

#include <Eigen/Geometry>
#include <unordered_set>

using Slic3r::Domain::Model;
using Slic3r::Domain::ModelObject;
using Slic3r::Domain::SLA::PointsStatus;
using Slic3r::Domain::SLA::SupportPoint;
using Slic3r::Domain::SLA::SupportPointType;
using Slic3r::Domain::Transform3d;
using Slic3r::Domain::Vec3f;
using Slic3r::Domain::Vec3d;
using Slic3r::Domain::Vec2d;
using Slic3r::Domain::Vec4d;
using Slic3r::App::Plater::apply_generated_points_on_leaving;
using Slic3r::App::Plater::apply_generated_support_points;
using Slic3r::App::Plater::sla_support_points_drawing_trafo;
using Slic3r::App::Plater::sla_support_points_hit_position;
using Slic3r::App::Plater::sla_support_points_lift;
using Slic3r::App::Plater::SlaSupportPointsLiftAction;
using Slic3r::App::Plater::SlaSupportPointsLiftDecision;
using Slic3r::App::Plater::sla_new_support_setting_changed;
using Slic3r::App::Plater::SlaSupportPointsEditing;
using Slic3r::App::Plater::SupportGeometryField;

namespace {

// Helper function that applies a transform to support points
// This mimics the world->mesh conversion done by SlaSupportPointsRequest
Slic3r::Domain::SLA::SupportPoints transform_support_points(
    const Slic3r::Domain::SLA::SupportPoints& points,
    const Transform3d& transform)
{
    Slic3r::Domain::SLA::SupportPoints result;
    result.reserve(points.size());
    for (const auto& sp : points) {
        SupportPoint transformed = sp;
        transformed.pos = (transform * sp.pos.cast<double>()).cast<float>();
        result.push_back(transformed);
    }
    return result;
}

// A model with one object and the given points on it, as the support tool finds the object it works
// on. The status is what the object carried before the tool did anything to it.
Model make_model(
    const Slic3r::Domain::SLA::SupportPoints& points,
    PointsStatus status = PointsStatus::UserModified
)
{
    Model model;
    ModelObject* object        = model.add_object();
    object->name               = "TestObject";
    object->sla_support_points = points;
    object->sla_points_status  = status;
    return model;
}

// The points a generation produced: they live in the tool (SlaSupportPointsGizmo's
// m_generated_support_points) and on no model until they are applied.
Slic3r::Domain::SLA::SupportPoints generated_points()
{
    Slic3r::Domain::SLA::SupportPoints points;
    points.push_back({Vec3f{10.f, 20.f, 5.f}, 0.2f, SupportPointType::slope});
    points.push_back({Vec3f{12.f, 18.f, 4.f}, 0.2f, SupportPointType::island});
    points.push_back({Vec3f{9.f, 22.f, 6.f}, 0.2f, SupportPointType::slope});
    return points;
}

} // namespace

// M2.31: the tool kept the points a generation produced to itself until Apply was pressed, so closing
// it dropped them and the model fell back onto the plate. The tests play the parts the gizmo plays:
// the points wait in the tool, and what leaving the tool does with them is what is asked here. The
// model write itself is apply_generated_support_points, the one write of generated points.
TEST_CASE(
    "SlaSupportPointsGizmo - leaving the tool keeps the generated points",
    "[SlaSupportPointsGizmo][leaving]"
)
{
    SECTION("Leaving the tool applies the points a generation produced")
    {
        Model model                                      = make_model({});
        ModelObject* object                              = model.objects.front();
        const Slic3r::Domain::SLA::SupportPoints pending = generated_points();

        // The tool is closed with the generated points still waiting for Apply.
        REQUIRE(apply_generated_points_on_leaving(
            /* has_generated_points */ true,
            /* discard_requested */ false
        ));
        apply_generated_support_points(*object, pending);

        REQUIRE(object->sla_support_points.size() == 3u);
        CHECK(object->sla_points_status == PointsStatus::AutoGenerated);
        for (size_t i = 0; i < pending.size(); ++i) {
            CHECK(object->sla_support_points[i] == pending[i]);
        }
    }

    SECTION("Leaving the tool writes nothing when no generation produced points yet")
    {
        Model model         = make_model({});
        ModelObject* object = model.objects.front();

        // A generation that is still running has no result to write: it is cancelled with the tool.
        CHECK_FALSE(apply_generated_points_on_leaving(
            /* has_generated_points */ false,
            /* discard_requested */ false
        ));
        CHECK(object->sla_support_points.empty());
    }

    SECTION("Leaving the tool writes nothing when there is nothing pending at all")
    {
        CHECK_FALSE(apply_generated_points_on_leaving(
            /* has_generated_points */ false,
            /* discard_requested */ false
        ));
    }

    SECTION("Discard throws the generated points away, so leaving writes nothing")
    {
        Model model         = make_model({});
        ModelObject* object = model.objects.front();

        // Discard clears the points before it closes the tool, which is what leaves the tool with
        // nothing to apply.
        CHECK_FALSE(apply_generated_points_on_leaving(
            /* has_generated_points */ true,
            /* discard_requested */ true
        ));

        CHECK(object->sla_support_points.empty());
        CHECK(object->sla_points_status == PointsStatus::UserModified);
    }

    SECTION("Discard of an object that has points leaves them as they were")
    {
        const Slic3r::Domain::SLA::SupportPoints existing{
            SupportPoint{Vec3f{1.f, 2.f, 3.f}, 0.5f, SupportPointType::manual_add}
        };
        Model model         = make_model(existing);
        ModelObject* object = model.objects.front();

        // The generator made nothing for this object, so there is nothing to discard either.
        CHECK_FALSE(apply_generated_points_on_leaving(
            /* has_generated_points */ false,
            /* discard_requested */ true
        ));

        REQUIRE(object->sla_support_points.size() == 1u);
        CHECK(object->sla_support_points.front() == existing.front());
    }
}

TEST_CASE(
    "SlaSupportPointsGizmo - an edit session left by deactivation keeps its edits",
    "[SlaSupportPointsGizmo][leaving]"
)
{
    // The edits of a session are written on the model after every edit
    // (SlaSupportPointsGizmo::commit_edited_points_live), so leaving the tool with the session open
    // has nothing to add and nothing to take away: end_editing() must not put back the points the
    // session started from.
    Model model =
        make_model({SupportPoint{Vec3f{1.f, 2.f, 3.f}, 0.5f, SupportPointType::manual_add}});
    ModelObject* object = model.objects.front();

    SlaSupportPointsEditing editing;
    editing.points = object->sla_support_points;
    editing.add_point(Vec3d{7., 8., 9.});
    editing.move_point(0, Vec3d{4., 5., 6.});
    object->sla_support_points = editing.points;
    object->sla_points_status  = PointsStatus::UserModified;

    CHECK_FALSE(apply_generated_points_on_leaving(
        /* has_generated_points */ false,
        /* discard_requested */ false
    ));

    REQUIRE(object->sla_support_points.size() == 2u);
    CHECK(object->sla_support_points[0].pos == Vec3f{4.f, 5.f, 6.f});
    CHECK(object->sla_support_points[1].pos == Vec3f{7.f, 8.f, 9.f});
    CHECK(object->sla_points_status == PointsStatus::UserModified);
}

TEST_CASE("SlaSupportPointsGizmo - transform_support_points", "[SlaSupportPointsGizmo]")
{
    SECTION("Transforms empty points to empty points")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        Transform3d transform = Transform3d::Identity();

        auto result = transform_support_points(input, transform);

        REQUIRE(result.empty());
    }

    SECTION("Identity transform preserves points")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::island});
        input.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::slope});
        Transform3d transform = Transform3d::Identity();

        auto result = transform_support_points(input, transform);

        REQUIRE(result.size() == 2);
        REQUIRE(result[0].pos == Vec3f{10.0f, 20.0f, 5.0f});
        REQUIRE(result[0].head_front_radius == 0.5f);
        REQUIRE(result[0].type == SupportPointType::island);
        REQUIRE(result[1].pos == Vec3f{15.0f, 25.0f, 6.0f});
        REQUIRE(result[1].head_front_radius == 0.6f);
        REQUIRE(result[1].type == SupportPointType::slope);
    }

    SECTION("Translation transform shifts points")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::island});
        Transform3d transform = Transform3d::Identity();
        transform.translate(Vec3d{5.0, -3.0, 2.0});

        auto result = transform_support_points(input, transform);

        REQUIRE(result.size() == 1);
        REQUIRE(result[0].pos == Vec3f{15.0f, 17.0f, 7.0f});
        REQUIRE(result[0].head_front_radius == 0.5f);
        REQUIRE(result[0].type == SupportPointType::island);
    }

    SECTION("Scaling transform scales points")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::island});
        Transform3d transform = Transform3d::Identity();
        transform.scale(Vec3d{2.0, 0.5, 1.0});

        auto result = transform_support_points(input, transform);

        REQUIRE(result.size() == 1);
        REQUIRE(result[0].pos == Vec3f{20.0f, 10.0f, 5.0f});
        REQUIRE(result[0].head_front_radius == 0.5f);
        REQUIRE(result[0].type == SupportPointType::island);
    }

    SECTION("Rotation transform rotates points around Z")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 0.0f, 5.0f}, 0.5f, SupportPointType::island});
        Transform3d transform = Transform3d::Identity();
        transform.rotate(Eigen::AngleAxisd(M_PI / 2, Vec3d::UnitZ()));

        auto result = transform_support_points(input, transform);

        REQUIRE(result.size() == 1);
        REQUIRE(std::abs(result[0].pos.x()) < 0.001f);
        REQUIRE(std::abs(result[0].pos.y() - 10.0f) < 0.001f);
        REQUIRE(result[0].pos.z() == 5.0f);
        REQUIRE(result[0].head_front_radius == 0.5f);
        REQUIRE(result[0].type == SupportPointType::island);
    }

    SECTION("Multiple points transformed correctly")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::island});
        input.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::slope});
        input.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::manual_add});
        Transform3d transform = Transform3d::Identity();
        transform.translate(Vec3d{1.0, 2.0, 3.0});

        auto result = transform_support_points(input, transform);

        REQUIRE(result.size() == 3);
        REQUIRE(result[0].pos == Vec3f{11.0f, 22.0f, 8.0f});
        REQUIRE(result[0].head_front_radius == 0.5f);
        REQUIRE(result[0].type == SupportPointType::island);
        REQUIRE(result[1].pos == Vec3f{16.0f, 27.0f, 9.0f});
        REQUIRE(result[1].head_front_radius == 0.6f);
        REQUIRE(result[1].type == SupportPointType::slope);
        REQUIRE(result[2].pos == Vec3f{6.0f, 32.0f, 7.0f});
        REQUIRE(result[2].head_front_radius == 0.4f);
        REQUIRE(result[2].type == SupportPointType::manual_add);
    }

    SECTION("Inverse transform recovers original points within tolerance")
    {
        Slic3r::Domain::SLA::SupportPoints input;
        input.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::island});
        input.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::slope});
        input.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::manual_add});
        Transform3d transform = Transform3d::Identity();
        transform.translate(Vec3d{1.0, 2.0, 3.0});
        transform.rotate(Eigen::AngleAxisd(M_PI / 4, Vec3d::UnitZ()));
        transform.scale(Vec3d{1.2, 0.8, 1.0});

        auto transformed = transform_support_points(input, transform);
        auto recovered = transform_support_points(transformed, transform.inverse());

        REQUIRE(recovered.size() == input.size());
        for (size_t i = 0; i < input.size(); ++i) {
            REQUIRE(std::abs(recovered[i].pos.x() - input[i].pos.x()) < 1e-5f);
            REQUIRE(std::abs(recovered[i].pos.y() - input[i].pos.y()) < 1e-5f);
            REQUIRE(std::abs(recovered[i].pos.z() - input[i].pos.z()) < 1e-5f);
            REQUIRE(recovered[i].head_front_radius == input[i].head_front_radius);
            REQUIRE(recovered[i].type == input[i].type);
        }
    }
}

TEST_CASE("SlaSupportPointsEditing - pure editing logic", "[SlaSupportPointsGizmo][editing]")
{
    SECTION("Add point creates manual_add point with correct head radius")
    {
        SlaSupportPointsEditing editor;
        editor.support_geometry.tip_diameter_mm = 0.6;

        editor.add_point(Vec3d{10.0, 20.0, 5.0});

        REQUIRE(editor.points.size() == 1);
        REQUIRE(editor.points[0].pos == Vec3f{10.0f, 20.0f, 5.0f});
        REQUIRE(editor.points[0].head_front_radius == 0.3f);
        REQUIRE(editor.points[0].type == SupportPointType::manual_add);
    }

    SECTION("Find nearest returns index within radius")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});

        auto idx = editor.find_nearest_point(Vec3d{10.1, 20.1, 5.1}, 1.0);

        REQUIRE(idx.has_value());
        REQUIRE(*idx == 0);
    }

    SECTION("Find nearest returns nullopt outside radius")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});

        auto idx = editor.find_nearest_point(Vec3d{100.0, 200.0, 50.0}, 1.0);

        REQUIRE(!idx.has_value());
    }

    SECTION("Find nearest returns closest point when multiple in radius")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{10.5f, 20.5f, 5.5f}, 0.6f, SupportPointType::island});

        auto idx = editor.find_nearest_point(Vec3d{10.1, 20.1, 5.1}, 2.0);

        REQUIRE(idx.has_value());
        REQUIRE(*idx == 0);
    }

    SECTION("Remove point removes correct index")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});

        editor.remove_point(1);

        REQUIRE(editor.points.size() == 2);
        REQUIRE(editor.points[0].pos == Vec3f{10.0f, 20.0f, 5.0f});
        REQUIRE(editor.points[1].pos == Vec3f{5.0f, 30.0f, 4.0f});
    }

    SECTION("Remove point handles out of bounds gracefully")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});

        editor.remove_point(5);

        REQUIRE(editor.points.size() == 1);
    }

    SECTION("Move point updates position")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});

        editor.move_point(0, Vec3d{12.0, 22.0, 7.0});

        REQUIRE(editor.points.size() == 1);
        REQUIRE(editor.points[0].pos == Vec3f{12.0f, 22.0f, 7.0f});
        REQUIRE(editor.points[0].head_front_radius == 0.5f);
        REQUIRE(editor.points[0].type == SupportPointType::manual_add);
    }

    SECTION("Move point handles out of bounds gracefully")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});

        editor.move_point(5, Vec3d{12.0, 22.0, 7.0});

        REQUIRE(editor.points.size() == 1);
        REQUIRE(editor.points[0].pos == Vec3f{10.0f, 20.0f, 5.0f});
    }

    SECTION("Head diameter affects new points only")
    {
        SlaSupportPointsEditing editor;
        editor.support_geometry.tip_diameter_mm = 0.4;
        editor.add_point(Vec3d{0, 0, 0});

        editor.support_geometry.tip_diameter_mm = 1.0;
        editor.add_point(Vec3d{1, 1, 1});

        REQUIRE(editor.points[0].head_front_radius == 0.2f);
        REQUIRE(editor.points[1].head_front_radius == 0.5f);
    }

    SECTION("Multiple edits sequence: add, move, remove")
    {
        SlaSupportPointsEditing editor;
        editor.support_geometry.tip_diameter_mm = 0.5;

        editor.add_point(Vec3d{0, 0, 0});
        editor.add_point(Vec3d{10, 10, 10});
        REQUIRE(editor.points.size() == 2);

        editor.move_point(0, Vec3d{1, 1, 1});
        REQUIRE(editor.points[0].pos == Vec3f{1.0f, 1.0f, 1.0f});

        editor.remove_point(0);
        REQUIRE(editor.points.size() == 1);
        REQUIRE(editor.points[0].pos == Vec3f{10.0f, 10.0f, 10.0f});
    }
}

TEST_CASE("SlaSupportPointsEditing - selection logic", "[SlaSupportPointsGizmo][selection]")
{
    SECTION("Select single point")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});

        editor.select_point(0);
        REQUIRE(editor.selected_point_indices.size() == 1);
        REQUIRE(editor.selected_point_indices.count(0) == 1);
    }

    SECTION("Shift+click adds to selection")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});

        editor.select_point(0);
        editor.select_point(1, true); // add to selection

        REQUIRE(editor.selected_point_indices.size() == 2);
        REQUIRE(editor.selected_point_indices.count(0) == 1);
        REQUIRE(editor.selected_point_indices.count(1) == 1);
    }

    SECTION("Shift+click removes from selection (toggle_point)")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});

        editor.select_point(0);
        editor.select_point(1, true);
        editor.toggle_point(0); // toggle off

        REQUIRE(editor.selected_point_indices.size() == 1);
        REQUIRE(editor.selected_point_indices.count(1) == 1);
    }

    SECTION("Select all selects all non-locked points")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});
        editor.lock_island_supports = true;

        editor.select_all_points();

        REQUIRE(editor.selected_point_indices.size() == 2);
        REQUIRE(editor.selected_point_indices.count(0) == 1); // manual_add
        REQUIRE(editor.selected_point_indices.count(2) == 1); // slope
        REQUIRE(editor.selected_point_indices.count(1) == 0); // island (locked)
    }

    SECTION("Select all selects all points when not locked")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});
        editor.lock_island_supports = false;

        editor.select_all_points();

        REQUIRE(editor.selected_point_indices.size() == 3);
    }

    SECTION("Clear selection removes all selected points")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});

        editor.select_point(0);
        editor.select_point(1, true);
        editor.clear_selection();

        REQUIRE(editor.selected_point_indices.empty());
    }

    SECTION("Delete selected removes selected non-locked points")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});
        editor.lock_island_supports = true;

        editor.select_point(0);
        editor.select_point(2, true); // select manual_add and slope
        editor.delete_selected_points();

        REQUIRE(editor.points.size() == 1);
        REQUIRE(editor.points[0].type == SupportPointType::island); // only island remains
        REQUIRE(editor.selected_point_indices.empty());
    }

    SECTION("Delete selected with lock off removes all selected including islands")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});
        editor.lock_island_supports = false;

        editor.select_point(0);
        editor.select_point(1, true);
        editor.select_point(2, true);
        editor.delete_selected_points();

        REQUIRE(editor.points.empty());
        REQUIRE(editor.selected_point_indices.empty());
    }

    SECTION("Delete selected does nothing when no points selected")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});

        editor.delete_selected_points();

        REQUIRE(editor.points.size() == 1);
    }

    SECTION("Apply head diameter to selected updates only selected points")
    {
        SlaSupportPointsEditing editor;
        editor.support_geometry.tip_diameter_mm = 0.4;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.2f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.3f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});

        editor.select_point(0);
        editor.select_point(2, true);
        editor.support_geometry.tip_diameter_mm = 1.0;
        editor.apply_support_geometry_to_selected(SupportGeometryField::TipDiameter);

        REQUIRE(editor.points[0].head_front_radius == 0.5f); // updated
        REQUIRE(editor.points[1].head_front_radius == 0.3f); // not selected, unchanged
        REQUIRE(editor.points[2].head_front_radius == 0.5f); // updated
    }

    SECTION("Remove point adjusts selected indices correctly")
    {
        SlaSupportPointsEditing editor;
        editor.points.push_back({Vec3f{10.0f, 20.0f, 5.0f}, 0.5f, SupportPointType::manual_add});
        editor.points.push_back({Vec3f{15.0f, 25.0f, 6.0f}, 0.6f, SupportPointType::island});
        editor.points.push_back({Vec3f{5.0f, 30.0f, 4.0f}, 0.4f, SupportPointType::slope});

        editor.select_point(1);
        editor.select_point(2, true);
        editor.remove_point(0); // remove first point

        REQUIRE(editor.points.size() == 2);
        // Selected indices should shift down by 1
        REQUIRE(editor.selected_point_indices.count(0) == 1); // was index 1
        REQUIRE(editor.selected_point_indices.count(1) == 1); // was index 2
    }
}

TEST_CASE("SlaSupportPointsEditing - rectangle selection", "[SlaSupportPointsGizmo][rectangle]")
{
    SECTION("Points inside rectangle are selected")
    {
        // Build screen positions directly (no camera needed)
        std::vector<Vec2d> screen_positions = {
            Vec2d{100, 200}, // point 0
            Vec2d{150, 250}, // point 1
            Vec2d{250, 300}  // point 2 (outside: x > 200)
        };

        // Rectangle covering first two points
        Vec2d rect_min{50, 50};
        Vec2d rect_max{200, 300};
        auto indices = SlaSupportPointsEditing::points_in_rectangle(screen_positions, rect_min, rect_max);

        REQUIRE(indices.size() == 2);
        REQUIRE(indices[0] == 0);
        REQUIRE(indices[1] == 1);
    }

    SECTION("Points outside rectangle are not selected")
    {
        std::vector<Vec2d> screen_positions = {
            Vec2d{100, 100}, // point 0
            Vec2d{200, 200}  // point 1
        };

        // Rectangle far away from points
        Vec2d rect_min{10, 10};
        Vec2d rect_max{20, 20};
        auto indices = SlaSupportPointsEditing::points_in_rectangle(screen_positions, rect_min, rect_max);

        REQUIRE(indices.empty());
    }

    SECTION("Rectangle selection works with partial overlap")
    {
        std::vector<Vec2d> screen_positions = {
            Vec2d{40, 40},   // point 0
            Vec2d{200, 200}, // point 1
            Vec2d{400, 400}  // point 2
        };

        // Rectangle covering first point only
        Vec2d rect_min{30, 30};
        Vec2d rect_max{60, 60};
        auto indices = SlaSupportPointsEditing::points_in_rectangle(screen_positions, rect_min, rect_max);

        REQUIRE(indices.size() == 1);
        REQUIRE(indices[0] == 0);
    }

    SECTION("Rectangle selection handles reversed corners (min > max)")
    {
        std::vector<Vec2d> screen_positions = {
            Vec2d{100, 100}, // point 0
            Vec2d{200, 200}, // point 1
            Vec2d{300, 300}  // point 2
        };

        // Rectangle with reversed corners (max first, then min)
        Vec2d rect_min{250, 250};
        Vec2d rect_max{50, 50};
        auto indices = SlaSupportPointsEditing::points_in_rectangle(screen_positions, rect_min, rect_max);

        // Should normalize and find points 0 and 1 (point 2 at 300 is outside)
        REQUIRE(indices.size() == 2);
        REQUIRE(indices[0] == 0);
        REQUIRE(indices[1] == 1);
    }
}

// M2.33: the lift of the object the tool works on. The scene draws a model lifted only when the M2.21
// support preview asks for it, which it does for a model that has support points, and the tool used
// to raycast and draw its point glyphs with the support elevation computed here instead. On a model
// with no points the two were 5 mm apart, so a click did not land on the surface that is drawn. The
// tool now takes the lift while it is open and works with the lift the scene actually applies, and
// these are the rules of that and of the raycast that follows it.
namespace {

// A 20 mm cube standing on the plate, where the object of the tool sits.
struct CubeOnThePlate
{
    Slic3r::AABBMesh aabb{Slic3r::Biz::Algorithms::TriangleMesh::its_make_cube(20., 20., 20.)};
    Transform3d      instance{Transform3d::Identity()};

    CubeOnThePlate()
    {
        instance.translate(Vec3d{100., 110., 0.});
    }
};

} // namespace

TEST_CASE("SlaSupportPointsGizmo - a click on the drawn model adds a point where the surface is",
          "[SlaSupportPointsGizmo][lift]")
{
    CubeOnThePlate cube;

    // The tool is open on a model with no support points, so the scene has no tree to draw and draws
    // the model where it is. The tool raises it by its support elevation, the way Chitubox raises the
    // model while the supports are edited (M2.33).
    const SlaSupportPointsLiftDecision decision = sla_support_points_lift(
        /* tool_open */ true,
        /* scene_lift */ 0.,
        /* support_elevation */ 5.,
        /* tool_owns_lift */ false
    );
    REQUIRE(decision.action == SlaSupportPointsLiftAction::Take);
    REQUIRE(decision.lift == Catch::Approx(5.));
    REQUIRE(decision.tool_owns_lift == true);

    // The raycast uses the lift the scene applies, and no other one.
    const Transform3d drawing = sla_support_points_drawing_trafo(cube.instance, decision.lift);

    // A click in the middle of the top face of the model as it is drawn.
    const Slic3r::App::Scene::Ray ray{Vec3d{110., 120., 60.}, Vec3d{0., 0., -1.}};
    const std::optional<Slic3r::Biz::Utils::MeshRaycaster::UnprojectResult> hit =
        Slic3r::Biz::Utils::MeshRaycaster::unproject_on_mesh(cube.aabb, ray, drawing);
    REQUIRE(hit.has_value());

    // The point of that hit is the clicked surface: the lift moved the model, not the point on it,
    // so the mesh position is the one the user clicked on.
    const Vec3d mesh_pos = sla_support_points_hit_position(Transform3d::Identity(), hit->position);
    CHECK(mesh_pos.x() == Catch::Approx(10.));
    CHECK(mesh_pos.y() == Catch::Approx(10.));
    CHECK(mesh_pos.z() == Catch::Approx(20.));

    // And the point the click places sits on the drawn surface, 5 mm above the plate.
    SlaSupportPointsEditing editing;
    sla_new_support_setting_changed(editing,
                                    Slic3r::App::Plater::SlaSupportPointField::TipDiameter,
                                    0.8);
    editing.add_point(mesh_pos);
    REQUIRE(editing.points.size() == 1u);
    const Vec3d world_pos = drawing * editing.points.front().pos.cast<double>();
    CHECK(world_pos.x() == Catch::Approx(110.));
    CHECK(world_pos.z() == Catch::Approx(25.));
    CHECK(editing.points.front().head_front_radius == Catch::Approx(0.4));

    SECTION("A separately computed elevation is a trafo the model is not drawn with")
    {
        // What the tool used to do: the support elevation of the object computed here, while the
        // scene draws the model on the plate. Every hit was then on a surface that is 5 mm away from
        // the one the user clicked on.
        const Transform3d drawn    = sla_support_points_drawing_trafo(cube.instance, 0.);
        const Transform3d old_tool = sla_support_points_drawing_trafo(cube.instance, 5.);
        const Vec3d       mesh_top = Vec3d{10., 10., 20.};

        CHECK((drawn * mesh_top).z() == Catch::Approx(20.));
        CHECK((old_tool * mesh_top).z() == Catch::Approx(25.));
        // One lift for the drawing, the raycast and the glyphs: the trafo the raycast is built from is
        // the one the decision asked the scene for.
        CHECK((drawing * mesh_top).isApprox(old_tool * mesh_top));
    }
}

TEST_CASE("SlaSupportPointsGizmo - the tool owns the lift of its object for as long as it is open",
          "[SlaSupportPointsGizmo][lift]")
{
    SECTION("A model with no points is raised while the tool is open and lowered again when it closes")
    {
        // Nothing lifts the model yet: the support preview has no tree for it.
        const SlaSupportPointsLiftDecision decision = sla_support_points_lift(true, 0., 5., false);
        CHECK(decision.action == SlaSupportPointsLiftAction::Take);
        CHECK(decision.lift == Catch::Approx(5.));
        CHECK(decision.tool_owns_lift == true);

        // The tool closes: the model falls onto the plate again, where the scene drew it before.
        const SlaSupportPointsLiftDecision leaving =
            sla_support_points_lift(false, decision.lift, 5., decision.tool_owns_lift);
        CHECK(leaving.action == SlaSupportPointsLiftAction::GiveBack);
        CHECK(leaving.lift == Catch::Approx(0.));
        CHECK(leaving.tool_owns_lift == false);
    }

    SECTION("A model with points keeps the lift of the support preview")
    {
        // The model has points now, so the preview service lifts it by exactly the support elevation.
        const SlaSupportPointsLiftDecision decision = sla_support_points_lift(true, 5., 5., true);
        CHECK(decision.action == SlaSupportPointsLiftAction::None);
        CHECK(decision.lift == Catch::Approx(5.));
        // The service holds this lift, so the tool does not take it away when it closes.
        CHECK(decision.tool_owns_lift == false);

        const SlaSupportPointsLiftDecision leaving = sla_support_points_lift(false, 5., 5., false);
        CHECK(leaving.action == SlaSupportPointsLiftAction::None);
        CHECK(leaving.lift == Catch::Approx(5.));
    }

    SECTION("A zero elevation is not lifted at all")
    {
        // Zero elevation, the object on the plate: the model is drawn there and raycast there.
        const SlaSupportPointsLiftDecision decision = sla_support_points_lift(true, 0., 0., false);
        CHECK(decision.action == SlaSupportPointsLiftAction::None);
        CHECK(decision.lift == Catch::Approx(0.));
        CHECK(decision.tool_owns_lift == false);
        CHECK(sla_support_points_drawing_trafo(Transform3d::Identity(), decision.lift)
              .isApprox(Transform3d::Identity()));
    }

    SECTION("A lift of the scene the tool did not take is never taken away")
    {
        // The preview service lifted the model by an elevation of its own (the object settings ask for
        // another one), so the tool works with that lift instead of over it.
        const SlaSupportPointsLiftDecision decision = sla_support_points_lift(true, 2., 5., false);
        CHECK(decision.action == SlaSupportPointsLiftAction::None);
        CHECK(decision.lift == Catch::Approx(2.));
        CHECK(decision.tool_owns_lift == false);
    }

    SECTION("An elevation that changes while the tool is open moves the model the tool lifted")
    {
        // The user raised support_object_elevation in the settings: the lift the tool took is stale,
        // and the tool follows the new one instead of leaving the model where it was.
        const SlaSupportPointsLiftDecision decision = sla_support_points_lift(true, 5., 8., true);
        CHECK(decision.action == SlaSupportPointsLiftAction::Take);
        CHECK(decision.lift == Catch::Approx(8.));
        CHECK(decision.tool_owns_lift == true);

        // And a zero elevation while the tool holds a lift hands it back.
        const SlaSupportPointsLiftDecision back = sla_support_points_lift(true, 8., 0., true);
        CHECK(back.action == SlaSupportPointsLiftAction::GiveBack);
        CHECK(back.lift == Catch::Approx(0.));
        CHECK(back.tool_owns_lift == false);
    }
}
