#!/usr/bin/env python3
"""Regenerate the progress section of README.md from doc/sla-fork/ROADMAP.md.

ROADMAP.md is the source of truth; this only summarises it. Run it after ticking a todo:

    python doc/sla-fork/tools/readme_progress.py

The section lives between the two PROGRESS markers in README.md and is replaced in full.
Everything outside the markers, including the upstream PrusaSlicer text, is left alone.
"""
from __future__ import annotations

import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
ROADMAP = ROOT / "doc" / "sla-fork" / "ROADMAP.md"
README = ROOT / "README.md"

START = "<!-- PROGRESS:START (generated by doc/sla-fork/tools/readme_progress.py; edit ROADMAP.md instead) -->"
END = "<!-- PROGRESS:END -->"

MILESTONE_RE = re.compile(r"^## (M\d+): (.+?)\s*$")
# IDs can contain hyphens (M5.3.pw-b1, M5.3.profiles-b); without them those todos were dropped.
ITEM_RE = re.compile(r"^(\s*)- \[( |x)\] \*\*(M[\w.-]+)\*\*\s*(.*)$")
BLOCKED_RE = re.compile(r"^\s+Blocked:\s*(.+)$")
ID_RE = re.compile(r"\bM\d+(?:\.[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)*\b")


def needs_of(rest: str) -> list[str]:
    """IDs from the 'needs ...' part of the trailer; 'needs —' means none."""
    for part in rest.split(" · "):
        part = part.strip()
        if part.startswith("needs"):
            return ID_RE.findall(part)
    return []


def short_title(rest: str) -> str:
    """The todo's description up to the size/needs trailer, trimmed for a one-line list."""
    title = rest.split(" · ")[0].strip()
    title = title.replace("`[human]`", "").replace("[human]", "").strip()
    return title if len(title) <= 110 else title[:107].rstrip() + "…"


def parse(text: str):
    milestones = []
    current = None
    last_item = None
    for line in text.splitlines():
        m = MILESTONE_RE.match(line)
        if m:
            current = {"id": m.group(1), "name": m.group(2), "items": [], "parked": False}
            milestones.append(current)
            last_item = None
            continue
        if current is None:
            continue
        if line.lstrip().startswith("> **Parked"):
            current["parked"] = True
            continue
        m = ITEM_RE.match(line)
        if m:
            last_item = {
                "id": m.group(3),
                "done": m.group(2) == "x",
                "human": "[human]" in m.group(4),
                "title": short_title(m.group(4)),
                "nested": len(m.group(1)) > 0,
                "blocked": None,
                "needs": needs_of(m.group(4)),
                "parked": current["parked"],
            }
            current["items"].append(last_item)
            continue
        m = BLOCKED_RE.match(line)
        if m and last_item is not None:
            last_item["blocked"] = m.group(1).strip()
    return milestones


def bar(done: int, total: int, width: int = 12) -> str:
    if total == 0:
        return ""
    filled = round(width * done / total)
    return "█" * filled + "░" * (width - filled)


def render(milestones) -> str:
    items = [i for m in milestones for i in m["items"]]
    done = sum(i["done"] for i in items)
    total = len(items)
    today = datetime.date.today().isoformat()

    out = [START, "", "## Progress", ""]
    out.append(
        f"**{done} of {total} todos done ({round(100 * done / total) if total else 0}%)** · "
        f"updated {today} · full list and result notes in "
        f"[`doc/sla-fork/ROADMAP.md`](doc/sla-fork/ROADMAP.md)"
    )
    out += ["", "| Milestone | Done | |", "|---|---|---|"]
    for m in milestones:
        md = sum(i["done"] for i in m["items"])
        mt = len(m["items"])
        name = f"{m['id']}: {m['name']}" + (" *(parked)*" if m["parked"] else "")
        pct = f"{round(100 * md / mt)}%" if mt else "–"
        out.append(f"| {name} | {md}/{mt} | `{bar(md, mt)}` {pct} |")

    done_ids = {i["id"] for i in items if i["done"]}
    # Only what can be acted on now: everything it needs is done, and its milestone is not parked.
    waiting = [
        i for i in items
        if not i["done"] and i["human"] and not i["parked"] and all(n in done_ids for n in i["needs"])
    ]
    if waiting:
        out += ["", "### Waiting on you", ""]
        out += [f"- **{i['id']}** {i['title']}" for i in waiting]

    blocked = [i for i in items if not i["done"] and i["blocked"]]
    if blocked:
        out += ["", "### Blocked", ""]
        out += [f"- **{i['id']}** {i['title']} — {i['blocked']}" for i in blocked]

    out += ["", "### Open todos", ""]
    for m in milestones:
        open_items = [i for i in m["items"] if not i["done"]]
        if not open_items:
            continue
        label = f"{m['id']}: {m['name']} — {len(open_items)} open" + (" (parked)" if m["parked"] else "")
        out += [f"<details><summary>{label}</summary>", ""]
        for i in open_items:
            indent = "  " if i["nested"] else ""
            tags = []
            if i["human"]:
                tags.append("needs you")
            if i["blocked"]:
                tags.append("blocked")
            suffix = f" *({', '.join(tags)})*" if tags else ""
            out.append(f"{indent}- [ ] **{i['id']}** {i['title']}{suffix}")
        out += ["", "</details>", ""]

    out.append(END)
    return "\n".join(out)


def main() -> int:
    section = render(parse(ROADMAP.read_text(encoding="utf-8")))
    readme = README.read_text(encoding="utf-8")
    if START in readme and END in readme:
        before = readme.split(START, 1)[0]
        after = readme.split(END, 1)[1]
        new = before + section + after
    else:
        print("README.md has no progress markers; add them where the section should go.", file=sys.stderr)
        return 1
    if new != readme:
        README.write_text(new, encoding="utf-8", newline="\n")
        print("README.md progress section updated.")
    else:
        print("README.md progress section already current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
